=== DirectorOfMe/directorof.me/apis/auth/json/schemas/slack.json
{
    "definitions": {
        "tokens": {
            "type": "object",
            "patternProperties": {
                "^.*_token$": {
                    "value": { "type": "string" },
                    "encryption": {
                        "anyOf": [
                            { "type": "null" },
                            {
                                "type": "string",
                                "enum": [ "RSA" ]
                            }
                        ]
                    }
                }
            },
            "additionalProperties": false
        }
    },


    "id": "https://matt.directorof.me/api/-/auth/app/slack",
    "$schema": "http://json-schema.org/draft-06/schema#",

    "description": "Schema for Slack App",
    "type": "object",

    "required": [ "user_id", "team_id", "scopes", "integrations" ],
    "additionalProperties": false,

    "properties": {
        "user_id": {
            "type": "string"
        },
        "team_id": {
            "type": "string"
        },
        "scopes": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "onboarding_complete": {
            "type": "boolean"
        },
        "integrations": {
            "type": "object",
            "patternProperties": {
                "^._token*$": { "$ref": "#/definitions/tokens" }
            },
			"additionalProperties": true
        }
    }
}

=== DirectorOfMe/directorof.me/apis/auth/json/examples/slack.json
{
    "user_id": "U23D7D5GU",
    "team_id": "T23D5K95J",
    "scopes": [ "identify", "bot", "commands", "dnd:read", "chat:write:bot", "dnd:write",
                "identity.basic", "identity.email" ],

    "onboarding_complete": false,

    "integrations": {
        "slack": {
			"configuration_url":"https://directorofme.slack.com/services/BAJMQFT33",
            "webhook_url": "https://hooks.slack.com/services/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",
            "access_token": {
                "encryption": "RSA",
                "value": "HEcQyT7hvYGaCQAPJy+yTooM2J3+ZiYhtu0lOg0niyK3D9DwLm1SGaTRCaNZGbZAXCweLigsMvL5zbENdS9v022W/en+ssLdnhGzxRm2l98nnJ/WpjRQ1qKf7tk/yA0EFbEkyB4Ab7Q9TevjXMixlC82VhC3b0fn72kKAWxitDf/7/MhiCf2H2JiAyOcnTQColbUuILEuMnUU0QWolwp5Jcz6FSY6XJsyFuqFFcw5mVn6GifXPp1w65yoeBoSnh5V+7DiAfLgQzyNYF0qJqrbLfyxbLJMKeUmWYcZvU9QLeeYOJJKgfmf0zDlyDF/YDbnmGhV91mZjaGpLW53naxByKfZvsa3RNcNmyNB3xr9ZKUg8tTRIO/ArheZz/MzHXqyoDQ6KuZ71DU1tf45dvwIYJtNq30blL8MOjGUime1xQ1d18H4RmOstdpOQ0e5NXKQVX5B9kuKDrSLMkn+SUT7uD/1YmewemHp3k7oRoXEWUInnlzP/X60b7493GYK05F6Oowr2cohw+24i/U0eJJf3v1KruSCrB/ETaIWeP0kKwQvGCRvMyYR0pmw8lqRZLg9yWDINME37+n8yjekZVpb0MRHkbBpcuUMlSwC4wE8BAIoH1MOivT95EIn12utRy6lL83+QqFX4gQ3JHb9HaxlfxaS1u+LuJ8E7KEaBY8qzY=;gAAAAABbE0Cpp9DlGjO01Tn5r6VTLI-LsoUiukxc-hCaNFUSqwcirZThQEdzh8nzomePArabXHZLaQ3m13VnbsCzEUR-lOQN368cqzf8F5hasKjgLYr5vUR9xaSYVex_Re8YG5wlJXhJbRJdjTvfNSIlZoBbsygFgg=="
            }
        },
        "directorofme": {
            "refresh_token": {
                "encryption": "RSA",
                "value": "KNVWpcGULSTG6Wg9t2/z9klp3zB3U9T7wMSINADWyKgLSXbkH3cTZ2PWgZWlSompBdfskqihmwD00cBx2upor7WUyHGWwsl8LLgWB2lgwZjPE0w3VdJLwonq69XupmxccFh3XLDZx02pBUEynolWizqyuD8VAMOTbTqsaHV0XrlYDzBsY9okd4Z9vjAQtLzKar9/guvVq92nAt/0Tzmk+DA/aJ2MzDe/c3mPeW4Xjyh2iEOQqp/9HS+JSzP5QmiwQblCieMhkUjz/RXWv+9wai4BsREKXEpoirQ4l6qJTHMckBn3T/YRJyzLpA2qAcU+1pR56qp1ASJr1o4+/uqABlt1aCB5YvyYGGLl5zIonSbydPmWKljW3ViZCmQd0aBVapcjDEHKEXKz/z2Ky7Ym1xuGnQdThsf+B74qZ9QBKVN2Rjf/7BPxuXPMtWnJJUcnsDKRx5QIjcgsbR/8Rh3PuQ8nnsdE5mSUw1dcHWLbs+SGX73bvkTHs4ARvIDBB8azFT2/zKzKj4ozcAXLLO3umuasYuW7KtAuud44iG4J1J0lS90v+seayAGJt9uMhe8fIXIzIPLGeAD6xqlArWYOrSCib6VEQwSpe8soHBBRmSwjVLt9ows79pyyuahVyqomv1V3wdsqebeBAk9nTAdzzcP4VwpAtCvx7Zm6WAA/SKE=;gAAAAABbE0ZMyxdJtOgGLY5gXaAkGoByEF2mc6NrOfleq0CKvEAuSEzshHM2Bg-KyXyaKOtuDys7PC1vXmVx-j70IpvKCWepg75tpWXbNM0su-99Gyd4cIeVBrp0sEebAg1JtPtfucCfXKmpOKScc34Njsl4LaXKXghupFEscLxxWkW3fTw4XC4JBHLh2g2XME26M3kZUTCqkReoGNi8bErJIGyB3_lm93GmfCxk33sWo4ExQN1q9FhVJqZJjA-nWJMHeEZJ_1BhmjT08PLgX2nNk3Dbrla9SyPTOWgrtRQ_IUxWggX0hNndDe9E3-BZXA45UaR6fpMmhO-yR5q3-u1BmXB8LiMCEdIaTTs7rw__y2JyvT72hQSnv2inifEtSmao5RAjU8QK6exQVIuCEzxQi3Fe3CZRxS_pghJjvO__gTjNHEJaBt04rXu1lg5itIp4B0x9L_roeKDZkzGWGPqksYZ-RCEO1L6OFiYgg_CyQUGyJHDliC2s57oGQNACX15GTJpj5JGlA-d0RK1WhDhORikrXAVIa8RIU0qtsZHkyJjLRtGAMzIegRGvNtDS5ufmTDhDPK-PXbkWPchcbjbWw1KgpWFkgWyT8CcT_BSn03fc7j-1_2rkQRAN6ri5p9bPNMQvq_1PdLMQW5QbqpUHOp1zS5lRvOZXvtkhcsQyLMluSPakPStf644JkPqR0OjcbX7rye6jpS7OyfNCbvPdvxfApuLc9piKxU19ZJRZ3q6pKs1L56ct7yKwVgT8HwdqEHpds5WRY85wnayQiIOX5uWxSVKtmssfkkDAaO3ta7OoQXYyQWpVdY_5SDHuZGjtDjkA8JElg4f_hLFEd-Ryfukbi7Lyhie4outalOPjm4zrBSmYKfUydqQ3raFhB1noM4-U5CA1oMF-B2uLYnak85U3syuNG0AoyFRNJvjVVnkrmUJXOpNMPxZ6hJMHbZKFnvGB9n-PtdZO0MKsHADZ1bDVVdp2qR0KClPZq6tCusZI5JVjMcS-wvv-KCJy9YFK_UcAruCpPir9gs6Wni04oa591hEPJGgpNNSXCfxuNo7xjAx0NmQ7VfnpPOHyImYZJp-BTgGNDuVfZqyYBPI2m-MyWyiFCrnzIueym4hKOG7pTpVCS6AoyxFoOMkf2YvMiOV4ELzVivfnmfkuYN3WM1vHkn54qnLHnkcuWTl7HTRGV-8sI_l7Ihsihb4FXY8PD_97bmBsSKQyLaEAbtzu7u11PpO9wp3AQrGHr9FLr3WhTB7C4q609MZnCE3K78r5oGFdTe7r3f2Agy677bAV7JILnGsCeGgwpFiw-_J5n7RNJVTx-RBOAC43qeBLRIQexv-ndxMrHDz5hPGuAqm5v6xz8zqR8gZhDvSu1-erJVrZS73IyD-iand0DdvL-uE1_UL3LWg_fyqp9RUHK6pdnxFCNquUA-HrU8Iwyj5p9FAceNZuuc7TrAovoi7twRIA_Ldld7ROwTaxK6z3lxFYjTBH4MNP4tf9xAZ-PwkAM49ZXa8_PtTy2jo49RWuk7F_vunhPFggMM1Z-9DjXflgsFxLKEdvM-2bsXlZDyjYY-Yhn2iPmHk5Ojws02mNVscfiCPPO3n2AA-HIHhEror9GWCdgbAE4vPCt5IaZCvKk_kOueMJink8NM9oh1fVG4uUc4ze1XM-8B2w5RcbHN4717IJnYJAkSihZrIfPSYU5vIwOB1BDUJBsBQE-lpsfp_JvFYpmh2GenbjDYrU0wk4pr6FLEjAH20UM3pwPfhfZFcv039yFz0HqYbE2VC--CYh-q2_LZqzu_tkqrliSelFuSnuHRbN5KyOGO1aGggihmFLQF7mt0EaaPxCKu_h4eEczEQgszBlqMCxrtvF8Yr879uXn9mKeKTx4AYGHrOjF4DiCNdFRdWDQ4dySe7MjplPfDISe_tAdMLbgG6WtPNJ83xFNqtAJukxwzbWtOEvMhNMUqfV7HIaLpAfZ4LHtjKM8kCOEMYze9VpguHx4n0k7GyomKKtzdGnOg7KR0-2-Hxw0kC8bKwaB-Xdkwmv02KD4gbZpGDNY9RhkzrkR197ePjO8eKeYX0ZSoWBjAT_YGfxGg-3voaWrCx6OFF5btuAKf99jiubxZt-mCIJSUmT2EwDe900X2-6vEOK5AnswVUwSNJ6w22mETARBxfxF69QOUWJQrLSGb85g3hSKQwr9XQkimGAXThWpPPZXR53STZ70rBLdfBTizvya_uuXBT3eyTmOCrGOKJWdxIb9bLMMWMZA87TdcdzU7gnVMUjeypl4eIqIUnxUshUzdvx8fSzmtzahrlX7p1mv6FhFV7UjBPf63M1vaZgsALA1B_izjssprTee6vluKBpVMz4Czu2rfQhGvnaEOphLttDzLgbrJZT8bjLJrLrD7CioUFr2FQFIT8e_gGgWwFJwxwFF1bqlcPRXOKRZR0ePc5FapSY8fqitIxt-ZFwYhHK9UI-m9SzAsC8myLOwJnEFOqQ9BfM-AdhcoomA364qeqXp5jL3AOi8CEmD5v7FHIl9-DyefxqIMre1tVWq8AWRSl4SZKr1yGej4_JbImhL8Cr7pqubsXRlBFlbPtsha7O7wZm1B_TmFzK9Gx_s0tATNBITd-3oJ5gLhyFVlwQmVwSbbMNP3iTJ66RwLHdvD_zrdbMk9gnvfQ8yeJ_Z5wZlLClI0JlardIdkA6-SDE4WauYfX4xURs6Rh5sG4q5_GAV7dqBfMYVJNxVwiG0OywjpxXIv2cfDtQ84SEHaDJS-8WQOHP6C_pOS1HB__ORQs_N5JBP2WhdBIc8RMvInXmMs0duQfFMTP_wWsG7imXgFGs3ZDeWLVz_4SSnFUuXwUEzZToCNlHmV1Yz8LL8j6VbMiD3Tubg8YoLwpO7pZxmvl9722PD8e6o7CDZo5hzxG5akHVW8_NiyPnqckBQpO54Uv6icrOVf9tAquKsRFklsXaewGe0HF_STYUqe__IAkz_biPY2sXF3NebJ7rpcAmKUZ_Y7T-TcPs-UXS_xJq8HwHuyvNMIdQbthB0bmaEaSwsXAFxkVlAIH1LKXpOg28WvIbV_k1eF9od2lR6nTIdHa5xTfhSJIKw9sdbJbZ0NKrYF4JTwknXFaHVNbTHEkSNGcH3FWhpUP1A41cFqEW6O6CtAwOoVshVZN3CZIi0US382fnqN1QTq19UidvfxWbe0Kl7XZXltrAs35scic5Quvs2vlbrJJj89g1Fpbe0lWrC2nvwxAs1JIcfV9-LHmhVoMYPg7au8T1LyBsfhjML3bySpHAoI3ckZN5MkZTjvuda_trw-_fgQjC3cBP9zAedmjoJDdxtJyFROd-bQNww323o3ok4UEtcg7UvNh6sutHO5ItGBktNrwjwVOvbm0iRULegq1kBZRkAOPgpAT3UygSC-BfyA90BZkDCu-g6iJ7II0i5CoUphPdClhTKI0Wa8UCTlSe0-x6FXjGQITB-_h1si6K_t_opWdfTolQhzd-eETQGYG4XCV7jSr4QKamw6rzkU2vji_SAjCkgLqKnx7OKoJpxJJMIl_Bv8fkf7Su19Nj3lat-sAQmgmcwGgBUXWfr_FvWdA7oqppgKqv_8FqZ5bpNJDA5IxEJI6-G-p7RqMdP-0gxWFmwDo="
            }
        }
    }
}
